blank_issues_enabled: false
contact_links:
  - name: Questions, Sharing ideas, Other support
    url: https://github.com/fhatfield-ippon/hc-automatic-invoicing-ui/discussions
    about: Check out the community discussions.
